---

# The rpm requirements for rhis-builder-provisioner
rpm_requirements_list:
  - "ansible-core"
  - "git"
  - "vim"
  - "@container-management"
  - "python3-pip"
  - "bind-utils"
  - "iputils"

# WARNING: WE *WILL* OVERWRITE /etc/ansible/ansible.cfg
# we will back it up with the current iso8601basic datetimestamp
# provisioner galaxy configuration
rhah_refresh_token: "{{ automation_hub_token_vault }}"
rhah_refresh_token_cmd: "{{ automation_hub_refresh_token_cmd_vault }}"

# This helps us when dealing with the git repositories for rhis-builder-*
git_configs:
  - name: "user.name"
    scope: "global"
    value: "shawkingly"
  - name: "user.email"
    scope: "global"
    value: "cshaw@redhat.com"

# Use this value to provide a default domain name
# for network variables that use the domain
# it simplifies updates for environment
# alternately, you can override in the domain in individual variables.
default_domain: "example.ca"
default_network: "192.168.140"

# If we are starting from zero and do not have DNS configured yet. e.g. IdM will be our DNS
# We use these values to update the local /etc/hosts file on the provisioner, idm and satellite
# bootstrap systems so that we have basic name resolution for the bootstrap process
environment_hosts:
  - name: "rhis-provisioner.{{ default_domain }}"
    ip: "192.168.64.6"
  - name: "idm.{{ default_domain }}"
    ip: "{{ default_network }}.10"
  - name: "satellite.{{ default_domain }}"
    ip: "{{ default_network }}.11"

  # You can extend this e.g. if you want to add your VMware environment
  # Development environment subnet
  # - name: "vcenter.{{ default_domain }}"
  #   ip: "{{ default_network }}.30"
  # - name: "esx2.{{ default_domain }}"
  #   ip: "{{ default_network }}.32"
  # - name: "esx3.{{ default_domain }}"
  #   ip: "{{ default_network }}.33"
  # - name: "esx4.{{ default_domain }}"
  #   ip: "{{ default_network }}.34"
  # - name: "esx5.{{ default_domain }}"
  #   ip: "{{ default_network }}.35"
  # - name: "esx6.{{ default_domain }}"
  #   ip: "{{ default_network }}.36"

rhis_repo_path: "~/rhis/"
my_git_username: "{{ git_configs[0].value }}"
rhis_git_repos:
  - name: "rhis-builder-inventory"
    url: "https://github.com/{{ my_git_username }}/rhis-builder-inventory.git"   # you will want to change this to a private repository
    force: true
  - name: "rhis-provisioner-container"
    url: "https://github.com/{{ my_git_username }}/rhis-provisioner-container.git"
    force: true

vault_file_remote_path: "~/.ansible/vault"
